apiVersion: v1
kind: Service
metadata:
  namespace: elasticsearch
  name: elasticsearch-logging-external
spec:
  type: NodePort
  selector:
    app: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
